import { createClient } from "@supabase/supabase-js";
import fs from "fs";

const envFile = fs.readFileSync(".env", "utf-8");
const env = Object.fromEntries(
  envFile
    .split("\n")
    .filter((l) => l.includes("="))
    .map((l) => l.trim().split("="))
);

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY || env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const skillId = "9b902aa2-73e1-4148-8f62-93f0e5645cf9";

async function run() {
  console.log("Updating Skill #2: Agribusiness & Market Sales...");

  // 1. Fetch tracks for this skill
  const { data: tracks, error: tErr } = await supabase
    .from("tracks")
    .select("id, title, order_index")
    .eq("skill_id", skillId)
    .order("order_index");

  if (tErr || !tracks || tracks.length < 3) {
    console.error("Error fetching tracks:", tErr);
    return;
  }

  const track1Id = tracks[0].id;
  const track2Id = tracks[1].id;
  const track3Id = tracks[2].id;

  // Update Track titles
  await supabase.from("tracks").update({ title: "Track 1: Production Economics, Farm Finance and Capital Strategy" }).eq("id", track1Id);
  await supabase.from("tracks").update({ title: "Track 2: Commodity Grain Marketing, Futures and Price Hedging" }).eq("id", track2Id);
  await supabase.from("tracks").update({ title: "Track 3: Supply Chain Logistics, Contracts and Global Trade" }).eq("id", track3Id);

  // Delete existing steps
  await supabase.from("steps").delete().in("track_id", [track1Id, track2Id, track3Id]);

  // Steps Data (Graduate / PhD level content)
  const steps = [
    // Track 1
    {
      track_id: track1Id,
      title: "Production Economics, Diminishing Returns and Marginal Cost Optimization",
      order_index: 1,
      content: `### Microeconomic Foundations of Farm Production

Agricultural enterprise management requires a rigorous understanding of neoclassical production economics. The relationship between physical agricultural inputs (fertilizer, seed density, irrigation water, machinery hours) and physical agricultural outputs (grain yield, livestock weight gain) is governed by the Classical Production Function:

\`\`\`
Y = f(X1 | X2, X3, ... Xn)
\`\`\`

Where Y represents total output, X1 is the variable input (e.g. nitrogen fertilizer in kg/ha), and X2 through Xn represent fixed inputs (land base, climate, machinery capacity).

### The Three Stages of Agricultural Production

1. Stage I (Increasing & High Marginal Returns):
   - Total Physical Product (TPP) increases at an increasing rate, then at a decreasing rate.
   - Marginal Physical Product (MPP = delta Y / delta X) exceeds Average Physical Product (APP = Y / X).
   - In this stage, fixed resources are under-utilized. Economic rationality dictates that a farm manager should never stop adding inputs in Stage I because the average efficiency of the variable input is still rising.

2. Stage II (Rational Economic Production Zone):
   - Commences at the exact boundary where MPP = APP (maximum average physical efficiency) and terminates where MPP = 0 (maximum total yield).
   - In Stage II, both MPP and APP are declining, but MPP remains positive. All economically rational production must take place within this stage.

3. Stage III (Negative Marginal Returns & Input Toxicity):
   - MPP becomes negative (MPP < 0), causing Total Physical Product to decline.
   - Adding additional input (e.g. excessive nitrogen causing crop lodging or salinity buildup) actively reduces biological yield. Operating in Stage III is irrational.

### The Profit Maximization Equimarginal Principle

To determine the exact profit-maximizing input level within Stage II, the farm economist applies the Equimarginal Principle:

\`\`\`
Marginal Value Product (MVP) = Marginal Input Cost (MIC)
\`\`\`

Where:
- Marginal Value Product is the additional monetary revenue generated by one additional unit of input: \`MVP = MPP * P_output\`.
- Marginal Input Cost is the price per unit of the variable input: \`MIC = P_input\`.

Rearranging this condition establishes that optimal input application occurs where the Marginal Physical Product equals the input-to-output price ratio:
\`\`\`
MPP = P_input / P_output
\`\`\`

If fertilizer costs $1.20 per kg and grain sells for $0.24 per kg, the profit-maximizing farmer must apply fertilizer up to the point where the last kilogram applied yields exactly 5.0 kg of additional grain (1.20 / 0.24 = 5.0). Applying beyond this point yields less revenue than the cost of the fertilizer, even if total yield is still technically increasing.

### Enterprise Budgeting and the Economic Shutdown Rule

Every crop enterprise requires an enterprise budget itemizing:
- Variable (Operating) Costs: Seed, fertilizer, crop protection chemicals, fuel, drying, crop insurance, custom hire, and operating interest.
- Fixed (Ownership) Costs: Depreciation, machinery interest, land cash rent or mortgage amortization, property taxes, and full-time farm insurance.

In the short run, a farm should continue producing as long as gross revenue covers total variable costs (\`Price > Average Variable Cost\`), contributing toward fixed overhead. If market price falls below Average Variable Cost (\`Price < AVC\`), the economic shutdown rule is triggered and the farm minimizes losses by ceasing operations immediately.`
    },
    {
      track_id: track1Id,
      title: "Farm Financial Statements, Accrual Adjustments and Ratio Analysis",
      order_index: 2,
      content: `### Farm Financial Standards Council (FFSC) Framework

Modern agribusiness requires accounting standards tailored to biological assets. The Farm Financial Standards Council (FFSC) establishes standard methodologies for financial reporting across five core performance criteria: Liquidity, Solvency, Profitability, Repayment Capacity, and Financial Efficiency.

### Balance Sheet Construction: Market Value vs Cost-Basis

A complete agricultural balance sheet must present both cost-basis and market-value columns:
- Current Assets: Cash, prepaid farm expenses, marketable livestock, and unsold harvested grain inventory (valued at current local cash price minus delivery costs).
- Non-Current Assets: Breeding livestock, machinery, buildings, drainage tile improvements, and agricultural real estate.
- Liabilities: Operating credit line balances, accounts payable, accrued interest, machinery term debt, and real estate mortgages.
- Deferred Tax Liability: A market-value balance sheet must estimate deferred federal and state income taxes that would be triggered if all grain inventory, machinery, and appreciated farmland were liquidated.

### The Critical Cash-to-Accrual Conversion

Most agricultural producers file taxes on a cash accounting basis for tax management flexibility. However, cash accounting severely distorts true farm profitability due to year-end tax prepayments and delayed grain marketing. True Net Farm Income from Operations (NFIFO) requires accrual adjustments:

\`\`\`
Accrual Net Revenue = Cash Receipts 
+ Ending Crop & Livestock Inventory - Beginning Crop & Livestock Inventory 
+ Ending Accounts Receivable - Beginning Accounts Receivable 
- Ending Accounts Payable + Beginning Accounts Payable 
- Ending Prepaid Expenses + Beginning Prepaid Expenses
\`\`\`

### Diagnostic Financial Ratios and Institutional Benchmarks

1. Liquidity Ratios:
   - Current Ratio = Current Assets / Current Liabilities. Benchmark: Strong > 2.0; Vulnerable < 1.3.
   - Working Capital to Gross Farm Revenue = Working Capital / Gross Revenue. Benchmark: Strong > 30%.

2. Solvency Ratios:
   - Debt-to-Asset Ratio = Total Liabilities / Total Farm Assets. Benchmark: Strong < 30%; Vulnerable > 60%.
   - Equity-to-Asset Ratio = Total Farm Equity / Total Farm Assets. Benchmark: Strong > 70%.

3. Profitability Measures:
   - Return on Assets (ROA) = (Net Farm Income from Operations + Farm Interest Paid - Value of Unpaid Operator Labor & Management) / Average Total Farm Assets. Benchmark: Strong > 8.0%.
   - Return on Equity (ROE) = (Net Farm Income from Operations - Value of Unpaid Operator Labor & Management) / Average Total Farm Equity. If ROE exceeds ROA, borrowed capital is earning more than its interest cost (positive financial leverage).

4. Repayment Capacity:
   - Term Debt Coverage Ratio (TDCR) = (Net Farm Income from Operations + Non-Farm Income + Depreciation + Interest on Term Debt - Family Living Expenses - Income Taxes) / (Annual Principal & Interest Payments on Term Debt). Benchmark: Strong > 1.50x; Critical < 1.10x.

5. Financial Efficiency:
   - Operating Expense Ratio = Total Operating Expenses (excluding depreciation) / Gross Farm Revenue. Benchmark: Strong < 65%; Vulnerable > 80%.`
    },
    {
      track_id: track1Id,
      title: "Agricultural Capital Budgeting, Land Valuation and Tax Strategy",
      order_index: 3,
      content: `### Capital Budgeting in Agribusiness

Long-term investments in agricultural infrastructure (center-pivot irrigation, grain storage bins, high-horsepower tractors, combine harvesters) require rigorous Discounted Cash Flow (DCF) capital budgeting:

\`\`\`
NPV = Sum [ CF_t / (1 + r)^t ] - Initial_Outlay
\`\`\`

Where CF_t represents net annual after-tax cash flows, r is the Weighted Average Cost of Capital (WACC) or hurdle rate, and t is the asset operational lifespan. An investment is economically viable only if Net Present Value is positive (NPV > 0) and the Internal Rate of Return (IRR) exceeds the cost of financing.

### Farmland Valuation Methodologies

Agricultural real estate comprises 80% to 85% of total farm sector assets. Farmland value is determined through three primary approaches:

1. Income Capitalization Approach:
   Farmland value is mathematically calculated as the present value of all future expected net rental earnings capitalized at the agricultural market capitalization rate:
\`\`\`
Farmland Value per Acre = Net Cash Rent / Capitalization Rate
\`\`\`
   If net annual cash rent (after property taxes and maintenance) is $280 per acre and the regional agricultural capitalization rate is 3.5%, the estimated economic value is $8,000 per acre ($280 / 0.035).

2. Soil Productivity Index (PI / CSR2) Valuation:
   Agronomists and appraisers benchmark land value against soil capability ratings (e.g. Corn Suitability Rating 2 - CSR2 or National Commodity Crop Productivity Index - NCCPI). A linear regression evaluates price per CSR2 point to standardize sales across heterogeneous topography and soil series.

3. Comparable Sales Approach:
   Adjusting recent public auction and private treaty land transactions for tile drainage status, field shape efficiency, road access, and local commercial grain elevator proximity.

### Machinery Economics and Capital Recovery Charge

Machinery ownership costs are modeled using the Capital Recovery Charge (CRC), which combines annual economic depreciation and the opportunity cost of invested capital:

\`\`\`
CRC = (Purchase_Price - Salvage_Value) * [ r / (1 - (1 + r)^-n) ] + (Salvage_Value * r)
\`\`\`

Where n is useful machine life in years and r is real cost of capital.

### Advanced Agricultural Tax Strategies

- Section 179 and Bonus Depreciation: Allows full immediate expensing of qualified new and used agricultural machinery, drainage tile, and single-purpose agricultural structures in the purchase year.
- Schedule J Farm Income Averaging: Allows farmers to elect to average all or part of current high farm income over the preceding three base tax years, preventing sudden pushes into top federal tax brackets during commodity boom cycles.
- Section 1031 Like-Kind Exchanges: Enables tax-deferred reinvestment of appreciated agricultural real estate proceeds into qualifying replacement farmland.`
    },

    // Track 2
    {
      track_id: track2Id,
      title: "Agricultural Commodity Markets, Price Discovery and Basis Dynamics",
      order_index: 1,
      content: `### The Structure of Commodity Futures Exchanges

Global agricultural price discovery centers on regulated futures exchanges, primarily the Chicago Board of Trade (CBOT/CME Group) for corn, soybeans, wheat, and soybean meal. Standard grain futures contracts specify:
- Standard Contract Volume: 5,000 bushels (approx 127 metric tons for corn/wheat, 136 metric tons for soybeans).
- Standard Deliverable Grades: #2 Yellow Corn, #1 Yellow Soybeans, #2 Soft Red Winter Wheat.
- Standard Delivery Months: E.g. Corn (March, May, July, September, December).

### The Fundamental Equation of Agricultural Cash Price

The price a farmer receives at their local commercial grain elevator, ethanol biorefinery, or river terminal is governed by the universal basis equation:

\`\`\`
Local Cash Price = Futures Price + Basis
\`\`\`

Where Basis is the spatial, temporal, and quality differential between the futures contract price at the exchange delivery point and the local cash delivery point. Basis can be positive ("over" futures) or negative ("under" futures).

### Microeconomic Drivers of Local Basis

Local basis reflects immediate physical cash supply and demand conditions:
1. Spatial Transportation Differentials: Freight costs (truck diesel, rail tariffs, river barge rates) required to move physical grain from the local origin to destination export ports (e.g. US Gulf or Pacific Northwest). High barge freight weakens (widens) local interior basis.
2. Local Processing Demand: Proximity to major ethanol plants, soybean crush facilities, or commercial feed mills creates strong positive local basis bids as processors compete to secure local bushels without paying inbound freight.
3. Storage Capacity and Harvest Congestion: During fall harvest, massive grain deliveries saturate local elevator storage, causing elevators to widen (weaken) basis to discourage deliveries. In spring, empty storage capacity and tight grain supplies cause elevators to narrow (strengthen) basis.

### Market Carry Structures: Contango vs Inverted Markets

- Carrying Charge Market (Contango):
  - Deferred futures contract months trade at a price premium to nearby contract months (e.g. March Corn at $4.80 vs December Corn at $4.65).
  - This spread represents the "Cost of Carry" (commercial interest cost on tied-up grain capital + physical storage warehouse fees + insurance). It signals the market to store grain post-harvest.
- Inverted Market (Backwardation):
  - Nearby futures contract months trade at a premium to deferred contract months (e.g. July Soybeans at $12.50 vs November Soybeans at $11.80).
  - An inverted market signals extreme immediate physical grain shortages and financially penalizes commercial grain storage, demanding immediate delivery into commercial processing channels.`
    },
    {
      track_id: track2Id,
      title: "Hedging Strategies with Futures Contracts",
      order_index: 2,
      content: `### The Mechanics of the Producer Short Hedge

Agricultural crop producers are naturally "long" physical grain. If market prices decline while the crop is growing in the field, farm revenue collapses. To eliminate price level risk, the producer executes a Short Hedge by selling futures contracts prior to harvest:

#### Step-by-Step Short Hedge Execution:
1. Pre-Planting / Growing Season:
   - In May, December Corn futures trade at $5.20/bu. Expected local harvest basis is -$0.30/bu under December futures.
   - The farmer sells 10 December Corn futures contracts (50,000 bushels) on the CME at $5.20/bu to lock in an expected net price of $4.90/bu ($5.20 - $0.30).
2. Harvest Delivery (Scenario A: Price Falls):
   - In November, market prices collapse. December Corn futures drop to $4.20/bu. The local cash elevator price is $3.90/bu (Basis is exactly -$0.30).
   - Cash Market Action: Farmer sells 50,000 bushels of physical corn to the local elevator at $3.90/bu, receiving $195,000.
   - Futures Market Action: Farmer buys back (offsets) the 10 December futures contracts at $4.20/bu, realizing a futures gain of $1.00/bu ($50,000 profit).
   - Net Realized Price: $3.90 cash + $1.00 futures gain = $4.90/bu. The price drop was 100% neutralized.
3. Harvest Delivery (Scenario B: Price Rallies):
   - In November, a severe drought pushes December futures to $6.20/bu. Local cash price rises to $5.90/bu (Basis is -$0.30).
   - Cash Market Action: Farmer sells physical corn at $5.90/bu, receiving $295,000.
   - Futures Market Action: Farmer buys back the futures contracts at $6.20/bu, suffering a futures loss of $1.00/bu (-$50,000).
   - Net Realized Price: $5.90 cash - $1.00 futures loss = $4.90/bu. The hedge locked in the target price but surrendered upside gains.

### Basis Risk in Agricultural Hedging

Hedging replaces volatile absolute price risk with substantially smaller basis risk. The net price received in a standard short hedge is defined as:

\`\`\`
Net Price Received = Futures Price Sold + Actual Basis at Delivery
\`\`\`

If basis strengthens from -$0.30 to -$0.15 (narrowing basis), the net realized price increases to $5.05/bu. If basis weakens to -$0.50 (widening basis), the net realized price declines to $4.70/bu.

### Margin Accounts and Cash Flow Management

To trade futures, market participants must maintain a brokerage margin account:
- Initial Margin: Upfront equity required to initiate a contract (e.g. $2,000 per 5,000-bushel corn contract).
- Maintenance Margin: Minimum equity threshold below which an immediate margin call is triggered.
- Daily Mark-to-Market: Accounts are settled daily against exchange closing prices. If a producer is short futures and the market rallies aggressively, the broker issues a cash Margin Call requiring immediate wire transfer of additional funds. Farmers must secure dedicated operating credit lines with lenders to finance margin calls during unexpected market rallies.`
    },
    {
      track_id: track2Id,
      title: "Agricultural Options: Puts, Calls and Structured Synthetic Positions",
      order_index: 3,
      content: `### Option Pricing Architecture in Commodity Trading

Commodity options provide price insurance without mandatory performance obligations:
- Put Option: Grants the buyer the legal right (not obligation) to sell a specific futures contract at a predetermined Strike Price on or before the expiration date.
- Call Option: Grants the buyer the right (not obligation) to buy a specific futures contract at the strike price.
- Premium: The market price paid by the option buyer to the option seller (writer). Option Premium consists of Intrinsic Value plus Extrinsic (Time) Value:

\`\`\`
Put Intrinsic Value = Max(0, Strike Price - Current Futures Price)
Call Intrinsic Value = Max(0, Current Futures Price - Strike Price)
\`\`\`

### Option Greeks in Agricultural Marketing

1. Delta (Hedge Ratio): Measures the expected change in option premium for every $1.00 move in the underlying futures contract. At-the-money options have a Delta of approximately 0.50.
2. Theta (Time Decay): Measures the rate at which an option's extrinsic time value decays per day. Theta decay accelerates exponentially as expiration approaches.
3. Vega: Measures option premium sensitivity to changes in Implied Volatility (IV). Before major USDA WASDE crop reports or during summer weather scares, high IV drives option premiums upward.

### Strategic Option Strategies for Crop Producers

#### 1. Protective Put Purchase (Establishing a Price Floor)
- Execution: Buy an at-the-money or slightly out-of-the-money Put option.
- Minimum Floor Price Formula:
\`\`\`
Expected Floor Price = Strike Price - Put Premium Paid + Expected Local Basis
\`\`\`
- Strategic Benefit: If prices crash, the value of the Put option rises cent-for-cent below the strike price. If prices rally, the Put is allowed to expire worthless while the farmer sells physical grain at the higher market price.

#### 2. Fence / Collar Strategy (Zero-Cost / Low-Cost Corridor)
- Execution: Purchase an out-of-the-money Put option (e.g. $4.80 strike for $0.25 premium) and simultaneously sell an out-of-the-money Call option (e.g. $5.60 strike for $0.25 premium).
- Financial Net Premium: $0.25 paid - $0.25 received = $0.00 net cost.
- Outcome: Establishes a guaranteed price floor at $4.80 while capping upside participation at $5.60. If market prices stay between $4.80 and $5.60, both options expire worthless and the farmer sells at local cash market rates.`
    },

    // Track 3
    {
      track_id: track3Id,
      title: "Cash Grain Contracting, Grain Elevators and Post-Harvest Logistics",
      order_index: 1,
      content: `### Commercial Grain Contracting Instruments

Farm managers utilize diverse contracting structures offered by commercial elevators and processing plants to separate futures pricing from basis determination:

1. Cash Forward Contract:
   - Fixes both the futures price and the local basis for delivery at a specified future date.
   - Pros: Simple, zero margin call exposure, locks in 100% of the price.
   - Cons: Inflexible; farmer must deliver physical bushels regardless of yield failure; no participation in market rallies.

2. Basis Contract:
   - Fixes the local basis (e.g. -$0.15 under July) but leaves the futures price open to be locked in at the farmer's discretion prior to contract expiration.
   - Optimal when local basis is historically strong but futures prices are expected to rally.

3. Hedge-to-Arrive (HTA) Contract:
   - Fixes the futures price on the CBOT exchange but leaves the local basis open to be established prior to delivery.
   - Optimal when futures prices reach target profit levels during spring rallies but harvest basis is currently wide and weak.

4. Price Later / Delayed Pricing (DP) Contract:
   - Title of physical grain transfers to the elevator upon delivery, but the cash price is established at a later date based on current market bids minus monthly elevator service fees.

### Grain Storage Economics and Physics

Storing grain on-farm to capture carry and basis appreciation requires calculating total storage holding costs:
- Opportunity Cost of Money: Value of grain inventory multiplied by the short-term operating interest rate.
- Grain Shrink Calculation: Loss of grain weight due to moisture reduction and handling. Total shrink is modeled as:
\`\`\`
Total Shrink % = Water Shrink % + Handling Loss (typically 0.50%)
Water Shrink % = ((Starting Moisture % - Target Moisture %) / (100% - Target Moisture %)) * 100
\`\`\`
  Drying corn from 20% to 15% moisture results in 5.88% water shrink + 0.50% handling loss = 6.38% total weight shrink.
- Aeration Management: Cooling grain in aerated bins using 0.1 to 0.5 Cfm/bushel airflow to maintain core grain temperature below 10 degrees C (50 degrees F), preventing insect reproduction and mold germination.

### FGIS Grain Grading and Quality Deductions

The USDA Federal Grain Inspection Service (FGIS) classifies grain quality:
- Test Weight: Minimum 56.0 lbs/bushel for #2 Yellow Corn, 54.0 lbs/bu for #1 Soybeans.
- Damaged Kernels (Total & Heat-Damaged): Mold, sprout, insect, or frost damage exceeding 5.0% triggers grade degradation.
- Foreign Material (FM): Broken corn and foreign material (BCFM) exceeding 3.0% incurs standard weight docking.
- Mycotoxins: Aflatoxin concentrations exceeding 20 parts per billion (ppb) or Vomitoxin (DON) exceeding 5 ppm trigger severe commercial price docking or total delivery rejection.`
    },
    {
      track_id: track3Id,
      title: "Identity Preserved (IP), Value-Added and Direct Agricultural Marketing",
      order_index: 2,
      content: `### Identity Preserved (IP) Specialty Crop Architecture

Commodity agricultural production operates on price-taking bulk homogeneity. In contrast, Identity Preserved (IP) systems capture substantial price premiums by producing and segregating specialty crops with verified genetic and processing traits:
- Specialty Crop Types: Non-GMO food-grade soybeans (clear hilum for tofu and soymilk), high-oleic soybeans, organic grains, white food corn, waxy corn, and malting barley.

### Rigorous Farm-Level Segregation Protocols

To capture IP premiums ($1.00 to $5.00+ per bushel), farm operators must eliminate commingling with conventional bulk commodities:
1. Planter & Seed Handling Cleanout: Complete vacuuming and cleanout of planter seed boxes, bulk seed tenders, and central fill hoppers prior to loading specialty seed.
2. Buffer Strips & Isolation Distances: Maintaining minimum spatial isolation distances (e.g. 30 to 100 feet) along field borders adjacent to conventional GMO crops to prevent cross-pollination.
3. Combine Harvester Flush: Harvesting and discarding (or marketing as conventional) the first 50 to 100 bushels through the combine header, threshing rotor, clean grain elevator, and grain tank before saving IP bushels.
4. Dedicated On-Farm Storage: Cleaned, sealed bins with dedicated augers and aeration fans to prevent cross-contamination.

### Direct-to-Consumer (D2C) and Value-Added Agribusiness

For horticultural and artisanal livestock enterprises, direct marketing bypasses wholesale intermediary margins:
- Community Supported Agriculture (CSA): Consumers purchase upfront seasonal subscriptions, providing the farm with interest-free working capital in early spring and sharing production risks.
- Food Hub Infrastructure: Regional food hubs aggregate product from small and mid-sized farms to provide standardized grading, temperature-controlled cold chains, and bulk distribution to institutional buyers (universities, hospital systems, regional grocery chains).
- Organic Certification (USDA National Organic Program): Requires a strict 3-year transition period with zero synthetic inputs, certified organic seed usage, detailed audit trails, and third-party inspection compliance.`
    },
    {
      track_id: track3Id,
      title: "Global Agricultural Trade, Farm Policy and Risk Management Programs",
      order_index: 3,
      content: `### Macroeconomic Drivers of Global Agricultural Trade

Agricultural commodities are traded globally in highly interconnected markets. Core macroeconomic price determinants include:
- Foreign Exchange Rates: A strengthening US Dollar makes domestic agricultural exports more expensive for foreign importers, suppressing export volume and weakening cash prices. Conversely, a devalued Brazilian Real or Argentine Peso incentivizes South American farmers to expand planted acreage and export aggressively.
- USDA WASDE Report Analysis: The monthly World Agricultural Supply and Demand Estimates (WASDE) report establishes the benchmark global balance sheet. Key metrics analyzed include:
\`\`\`
Ending Stocks = (Beginning Stocks + Total Production + Total Imports) - (Domestic Use + Exports)
Stocks-to-Use Ratio = (Ending Stocks / Total Use) * 100
\`\`\`
A declining Stocks-to-Use ratio below 10% for corn or 5% for soybeans signals acute supply scarcity and triggers aggressive commodity price rallies.

### Farm Bill Title I Safety Net Programs

In the United States, Title I commodity programs provide statutory risk mitigation:
1. Price Loss Coverage (PLC): Provides price support when the effective national marketing year average (MYA) price falls below the statutory Reference Price. Payments are decoupled from current production and paid on 85% of historical base acres.
2. Agriculture Risk Coverage - County (ARC-CO): Provides revenue-based protection when actual county crop revenue falls below 86% of the benchmark historical county revenue (Olympic average of historical 5-year yields multiplied by 5-year MYA prices).

### Federal Crop Insurance (RMA / USDA) Architecture

Multi-Peril Crop Insurance (MPCI) is the primary enterprise risk management tool in modern farming:
- Revenue Protection (RP): Insures against both physical yield loss and commodity market price declines. Revenue guarantee is calculated as:
\`\`\`
Revenue Guarantee = Approved APH Yield * Coverage Level (50% to 85%) * Max(Projected Spring Price, Harvest Fall Price)
\`\`\`
The "Harvest Price Exclusion" (RP-HPE) fixes the guarantee strictly to the projected spring price, lowering policy premiums.
- Supplemental Coverage Option (SCO) & Enhanced Coverage Option (ECO): County-level shallow-loss endorsements that stack on top of individual RP policies up to 90% or 95% of expected revenue.

### Trade Barriers and Geopolitical Risk

Agribusiness managers must navigate Sanitary and Phytosanitary (SPS) non-tariff barriers, bilateral tariff retaliations, and ocean container shipping disruptions through forward contracting and diversified counterparty risk management.`
    }
  ];

  for (const step of steps) {
    const { error: sErr } = await supabase.from("steps").insert(step);
    if (sErr) console.error("Step insert error:", sErr);
  }

  console.log("Successfully inserted 9 expert steps across 3 tracks for Skill #2.");

  // 2. Clear old quiz questions and insert 15 expert quiz questions
  await supabase.from("quiz_questions").delete().eq("skill_id", skillId);

  const quizQuestions = [
    // 5 EASY (Correct indices: 1, 3, 0, 2, 1)
    {
      skill_id: skillId,
      question_text: "What is the fundamental mathematical equation governing agricultural local cash price?",
      options: [
        "Local Cash Price = Futures Price multiplied by Basis",
        "Local Cash Price = Futures Price + Basis",
        "Local Cash Price = Basis minus Futures Price",
        "Local Cash Price = Operating Expenses divided by Yield"
      ],
      correct_option_index: 1,
      explanation: "Local Cash Price is universally calculated as Futures Price plus Basis, where Basis represents the local spatial, temporal, and quality differential relative to the exchange futures price.",
      difficulty: "easy",
      order_index: 1
    },
    {
      skill_id: skillId,
      question_text: "What standard physical volume of grain is represented by one standard futures contract on the Chicago Board of Trade (CBOT) for corn or soybeans?",
      options: [
        "1,000 bushels (approx 25 metric tons)",
        "2,500 bushels (approx 63 metric tons)",
        "10,000 bushels (approx 254 metric tons)",
        "5,000 bushels (approx 127 metric tons for corn)"
      ],
      correct_option_index: 3,
      explanation: "A standard grain futures contract on the CBOT/CME represents exactly 5,000 bushels of grain.",
      difficulty: "easy",
      order_index: 2
    },
    {
      skill_id: skillId,
      question_text: "In neoclassical agricultural production economics, which stage of production represents the rational economic operating zone where Marginal Physical Product (MPP) is positive but declining?",
      options: [
        "Stage II (between MPP = APP and MPP = 0)",
        "Stage I (where MPP exceeds APP)",
        "Stage III (where MPP is negative)",
        "Stage IV (where total output reaches zero)"
      ],
      correct_option_index: 0,
      explanation: "Stage II is the only economically rational production zone. It begins where average physical product is maximized (MPP = APP) and ends where total physical product is maximized (MPP = 0).",
      difficulty: "easy",
      order_index: 3
    },
    {
      skill_id: skillId,
      question_text: "Which financial document measures a farm enterprise's total assets, total liabilities, and net worth at a specific point in time?",
      options: [
        "Cash Flow Statement",
        "Enterprise Budget",
        "Balance Sheet (Net Worth Statement)",
        "Depreciation Schedule"
      ],
      correct_option_index: 2,
      explanation: "The Balance Sheet provides a point-in-time financial snapshot summarizing all current and non-current farm assets, liabilities, and owner equity.",
      difficulty: "easy",
      order_index: 4
    },
    {
      skill_id: skillId,
      question_text: "What is the primary objective of a crop producer who executes a Short Hedge by selling futures contracts during the growing season?",
      options: [
        "To speculate on wild price swings in financial markets",
        "To establish a guaranteed price floor and protect against falling cash grain prices before harvest",
        "To eliminate all future local grain transportation costs",
        "To borrow short-term cash directly from the commodity exchange"
      ],
      correct_option_index: 1,
      explanation: "A short hedge locks in a selling price for growing crops, neutralizing the risk of a market price decline prior to harvest delivery.",
      difficulty: "easy",
      order_index: 5
    },

    // 5 MODERATE (Correct indices: 2, 0, 3, 1, 2)
    {
      skill_id: skillId,
      question_text: "According to the Farm Financial Standards Council, what is the institutional benchmark for a financially strong Current Ratio on a commercial farm?",
      options: [
        "Less than 0.80",
        "Between 0.90 and 1.10",
        "Greater than 2.00",
        "Exactly 0.50"
      ],
      correct_option_index: 2,
      explanation: "A Current Ratio (Current Assets / Current Liabilities) above 2.0 indicates robust liquidity, ensuring the farm can meet all short-term operating obligations without liquidating breeding or capital assets.",
      difficulty: "moderate",
      order_index: 6
    },
    {
      skill_id: skillId,
      question_text: "Under the Equimarginal Principle in agricultural production economics, at what precise point is variable input application profit-maximized?",
      options: [
        "Where Marginal Value Product equals Marginal Input Cost (MVP = MIC)",
        "Where Total Physical Product reaches its absolute biological maximum",
        "Where Average Variable Cost equals Total Fixed Cost",
        "Where Marginal Physical Product reaches its highest numerical peak"
      ],
      correct_option_index: 0,
      explanation: "Profit maximization occurs where the monetary revenue generated by the last unit of input equals the cost of that input: MVP = MIC (or MPP = P_input / P_output).",
      difficulty: "moderate",
      order_index: 7
    },
    {
      skill_id: skillId,
      question_text: "In commodity options trading, which Option Greek measures the sensitivity of option premium to changes in Implied Volatility (IV) ahead of critical USDA WASDE crop reports?",
      options: [
        "Delta",
        "Theta",
        "Gamma",
        "Vega"
      ],
      correct_option_index: 3,
      explanation: "Vega measures option premium sensitivity to changes in implied volatility. Pre-report uncertainty spikes implied volatility, increasing option premiums across both puts and calls.",
      difficulty: "moderate",
      order_index: 8
    },
    {
      skill_id: skillId,
      question_text: "Under the Income Capitalization approach to agricultural real estate valuation, what is the estimated economic value of an acre of farmland generating $280 in net annual cash rent with a market capitalization rate of 3.5%?",
      options: [
        "$2,800 per acre",
        "$8,000 per acre",
        "$14,500 per acre",
        "$980 per acre"
      ],
      correct_option_index: 1,
      explanation: "Land Value = Net Cash Rent / Capitalization Rate = $280 / 0.035 = $8,000 per acre.",
      difficulty: "moderate",
      order_index: 9
    },
    {
      skill_id: skillId,
      question_text: "Which grain contracting agreement establishes the CBOT exchange futures price while leaving the local basis open to be locked in prior to final physical grain delivery?",
      options: [
        "Cash Forward Contract",
        "Basis Contract",
        "Hedge-to-Arrive (HTA) Contract",
        "Delayed Pricing (DP) Contract"
      ],
      correct_option_index: 2,
      explanation: "A Hedge-to-Arrive (HTA) contract locks in the futures price on the exchange while leaving the local basis component unpriced until delivery approaches.",
      difficulty: "moderate",
      order_index: 10
    },

    // 5 DIFFICULT (Correct indices: 0, 3, 1, 2, 0)
    {
      skill_id: skillId,
      question_text: "A grain producer harvests corn at 20% moisture and artificially dries it down to the commercial standard of 15% moisture. Incorporating the standard 0.50% handling loss, what is the total percentage weight shrink?",
      options: [
        "6.38%",
        "5.00%",
        "3.85%",
        "8.50%"
      ],
      correct_option_index: 0,
      explanation: "Water Shrink % = ((20 - 15) / (100 - 15)) * 100 = (5 / 85) * 100 = 5.88%. Total Shrink = 5.88% + 0.50% handling loss = 6.38%.",
      difficulty: "difficult",
      order_index: 11
    },
    {
      skill_id: skillId,
      question_text: "A commercial farm manager executes a Zero-Cost Fence (Collar) hedging strategy by purchasing an out-of-the-money $4.80 Put option for $0.25 premium and selling an out-of-the-money $5.60 Call option for $0.25 premium. What is the net financial payoff if the harvest futures price settles at $6.20?",
      options: [
        "The farmer receives the full $6.20 cash price plus a $0.50 option profit",
        "The farmer receives the minimum floor price of $4.80",
        "The farmer receives $0.00 because both options expire worthless",
        "The farmer's effective selling price is capped at $5.60 because the short call obligates delivery above the $5.60 strike"
      ],
      correct_option_index: 3,
      explanation: "In a collar strategy, selling the $5.60 Call finances the Put purchase but caps upside revenue at the $5.60 strike. Any market price above $5.60 is surrendered to cover the short call obligation.",
      difficulty: "difficult",
      order_index: 12
    },
    {
      skill_id: skillId,
      question_text: "In accrual accounting adjustments for farm businesses, how is true Net Farm Income from Operations calculated from cash accounting records when grain inventory increases and accounts payable increase during the tax year?",
      options: [
        "Add both ending inventory and ending accounts payable to cash receipts",
        "Add the increase in grain inventory and subtract the increase in accounts payable from cash receipts",
        "Subtract the increase in grain inventory and add ending accounts payable to cash receipts",
        "Disregard all inventory changes because biological assets are non-taxable until sold"
      ],
      correct_option_index: 1,
      explanation: "Accrual adjustments add ending inventory increases (earned unsold revenue) and subtract ending accounts payable increases (incurred unpaid expenses) from cash receipts.",
      difficulty: "difficult",
      order_index: 13
    },
    {
      skill_id: skillId,
      question_text: "What market condition is present when nearby commodity futures contracts trade at a premium to deferred contract months, and what economic signal does it transmit to commercial grain handlers?",
      options: [
        "Contango (Carrying Charge); signals handlers to build long-term grain storage infrastructure",
        "Normal Backwardation; signals that currency exchange rates have stabilized",
        "Inverted Market; signals acute immediate physical grain shortages and financially penalizes storage, demanding immediate delivery into processing channels",
        "Cost-of-Carry Equilibrium; signals that shipping tariffs have exceeded export values"
      ],
      correct_option_index: 2,
      explanation: "An inverted market occurs when nearby contracts trade higher than deferred contracts. This structure penalizes physical storage and economically forces grain into immediate commercial consumption.",
      difficulty: "difficult",
      order_index: 14
    },
    {
      skill_id: skillId,
      question_text: "Under USDA Risk Management Agency (RMA) Revenue Protection (RP) crop insurance, how is the final indemnity revenue guarantee determined when harvest fall prices exceed spring projected prices?",
      options: [
        "Revenue Guarantee = Approved APH Yield * Coverage Level (50% to 85%) * Harvest Fall Price",
        "Revenue Guarantee = Approved APH Yield * Coverage Level * Spring Projected Price only",
        "Revenue Guarantee = 5-year Olympic Average County Yield * Statutory Reference Price",
        "Revenue Guarantee = Total Farm Operating Expenses * 1.50"
      ],
      correct_option_index: 0,
      explanation: "Under standard Revenue Protection (without harvest price exclusion), the revenue guarantee automatically floats upward to use the higher Harvest Fall Price if market prices rally during the growing season.",
      difficulty: "difficult",
      order_index: 15
    }
  ];

  for (const q of quizQuestions) {
    const { error: qErr } = await supabase.from("quiz_questions").insert(q);
    if (qErr) console.error("Quiz question insert error:", qErr);
  }

  console.log("Successfully inserted 15 expert quiz questions with randomized correct answers.");
  console.log("Skill #2 update completed successfully!");
}

run();
